<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NeoCore.Application\NeoCore.Application.csproj" />
    <ProjectReference Include="..\NeoCore.Infrastructure.OutputPoint\NeoCore.Infrastructure.OutputPoint.csproj" />
  </ItemGroup>

</Project>
