// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeoCore.Infrastructure.OutputPoint.Database.SqlServer;

#nullable disable

namespace NeoCore.Infrastructure.OutputPoint.Database.SqlServer.Migraciones
{
    [DbContext(typeof(SqlServerContexto))]
    [Migration("20260710235045_AgregarIdempotencia")]
    partial class AgregarIdempotencia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ms-libro-mayor")
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NeoCore.Infrastructure.OutputPoint.Database.SqlServer.Entidades.EventoAlmacenEntidad", b =>
                {
                    b.Property<Guid>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdAgregado")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OcurrioEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoMensaje")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("IdEvento");

                    b.HasIndex("OcurrioEn")
                        .HasDatabaseName("IX_Eventos_OcurrioEn");

                    b.HasIndex("TipoMensaje")
                        .HasDatabaseName("IX_Eventos_TipoMensaje");

                    b.HasIndex("IdAgregado", "Version")
                        .IsUnique()
                        .HasDatabaseName("IX_Eventos_Agregado_Version");

                    b.ToTable("Eventos", "ms-libro-mayor");
                });

            modelBuilder.Entity("NeoCore.Infrastructure.OutputPoint.Database.SqlServer.Entidades.IdempotenciaEntidad", b =>
                {
                    b.Property<Guid>("IdClave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreComando")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("IdClave");

                    b.ToTable("Idempotencias", "ms-libro-mayor");
                });
#pragma warning restore 612, 618
        }
    }
}
